# Generated by Django 5.0 on 2023-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('university_name', models.CharField(max_length=300)),
                ('degree_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('start_end', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('tech_stack', models.CharField(max_length=300)),
                ('responsibilities', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('langauge', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_end', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('techstack', models.CharField(max_length=300)),
                ('responsibilities', models.CharField(max_length=300)),
                ('live_url', models.CharField(max_length=300)),
                ('github_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('bio', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
